### ISSUE TITLE
star 数值问题

### ISSUE THREAD

**Issue by isuudev** [azhong1011/RatingBar#1]
/**
     * 图片的点击事件
     */
    @Override
    public void onClick(View v) {
        Integer index = (Integer) v.getTag();
        star = index+1;
        fillingImage(index);
    }

//index +1

**Comment by azhon** [comment]
star代表的是当前评论的星级，index是每个view的下标（tag）从0开始，所以star=index +1

**Comment by isuudev** [comment]
对的，你改一下吧

**Comment by azhon** [comment]
你切换下分支 用最新的1.1.0版本，那里已经改好了。
